### ISSUE TITLE
My assignment is ready for grading

### ISSUE THREAD

**Issue by ChenyuWClaire** [VIS-2129-F2020/cwang2-vis#1]

**Comment by ChenyuWClaire** [comment]
https://vis-2129-f2020.github.io/cwang2-vis/assignment1

**Comment by bauranov** [comment]
Good work! Everything looks great, I have very little to add. Here are a couple of comments:
- Add a row between the code chunk and a header (text that starts with #) to format it properly in HTML. 
- Suppress messages in HTML by adding {r, message = FALSE}.

Keep up the good work!

Edit: one more thing, please assign me and Carol to every issue so your homework appears in our githubs. Thanks
