### ISSUE TITLE
assignment 3 up for grading & one odd graph

### ISSUE THREAD

**Issue by ChenyuWClaire** [VIS-2129-F2020/cwang2-vis#3]
https://vis-2129-f2020.github.io/cwang2-vis/singapore-ass3

The last graph is totally fine in my rmd file when I run it... But whenever I knit it, it appears to be a different graph. Even though I tried to reload the original dataset so as to avoid the influence of previous selections, it doesn't work on knit but works in R studio. I tried to resolve it during TA hours with Aleks... but it is still odd. So we agree to just upload the screenshot.....

Therefore, I also attached screenshot of the last graph!

**Comment by ChenyuWClaire** [comment]
Screen Shot 2020-09-25 at 10.31.02.png

**Comment by bauranov** [comment]
Good work! Looking forward to your next assignment.
