### ISSUE TITLE
interactive map for grading

### ISSUE THREAD

**Issue by ChenyuWClaire** [VIS-2129-F2020/cwang2-vis#5]
https://vis-2129-f2020.github.io/cwang2-vis/boston%20climate%20vulnerable%20population.html

**Comment by c-voulgaris** [comment]
Thanks! Please submit the html file via Canvas.

**Comment by ChenyuWClaire** [comment]
Got it! Thank you~

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Carole Turley Voulgaris <notifications@github.com>
Enviado: Tuesday, October 27, 2020 1:08:13 PM
Para: VIS-2129-F2020/cwang2-vis <cwang2-vis@noreply.github.com>
Cc: Wang, Claire <cwang2@gsd.harvard.edu>; Author <author@noreply.github.com>
Asunto: Re: [VIS-2129-F2020/cwang2-vis] interactive map for grading (#5)


Thanks! Please submit the html file via Canvas.
